export const listingsData = [
  {
    id: 1,
    listingId: "123-4567-89",
    name: "Sunnydale Estate",
    address: "123 Main St",
    city: "Springfield",
    state: "IL",
    zip: "62704",
    price: 450000,
    square_foot: 2800,
    bedrooms: 4,
    lot_size: 1.5,
    bathrooms: 3,
    listing_date: "2023-07-15",
    garage: 2,
    realtor: "John Doe",
    detail:
      "This beautiful Sunnydale Estate offers spacious living with 4 bedrooms and 3 bathrooms. The large lot size of 1.5 acres provides ample outdoor space for recreation and gardening. The home features modern amenities and a cozy atmosphere, perfect for families looking for a comfortable and elegant living space.",
    featured_image: "/images/home-1.jpg",
  },
  {
    id: 2,
    listingId: "234-5678-90",
    name: "Riverview Villa",
    address: "456 River Rd",
    city: "Metropolis",
    state: "NY",
    zip: "10001",
    price: 1200000,
    square_foot: 3500,
    bedrooms: 5,
    lot_size: 2.0,
    bathrooms: 4,
    listing_date: "2023-06-20",
    garage: 3,
    realtor: "Bruce Wayne",
    detail:
      "Riverview Villa is a luxurious 5-bedroom home with stunning river views. The property features 4 bathrooms, a large 2-acre lot, and a spacious 3-car garage. This villa offers high-end finishes and top-of-the-line appliances, making it an ideal choice for those seeking elegance and comfort in Metropolis.",
    featured_image: "/images/home-2.jpg",
  },
  {
    id: 3,
    listingId: "345-6789-01",
    name: "Greenfield Cottage",
    address: "789 Green St",
    city: "Gotham",
    state: "NJ",
    zip: "07001",
    price: 600000,
    square_foot: 2500,
    bedrooms: 3,
    lot_size: 0.8,
    bathrooms: 2,
    listing_date: "2023-05-10",
    garage: 2,
    realtor: "Kent Clark",
    detail:
      "Greenfield Cottage is a charming 3-bedroom home located in the heart of Gotham. This cozy cottage features 2 bathrooms, a spacious living area, and a well-maintained 0.8-acre lot. With its modern updates and classic design, this property is perfect for those seeking a peaceful retreat with convenient city access.",
    featured_image: "/images/home-3.jpg",
  },
  {
    id: 4,
    listingId: "456-7890-12",
    name: "Hilltop Manor",
    address: "321 Hilltop Dr",
    city: "Smallville",
    state: "KS",
    zip: "67524",
    price: 850000,
    square_foot: 3200,
    bedrooms: 4,
    lot_size: 1.2,
    bathrooms: 3,
    listing_date: "2023-04-25",
    garage: 2,
    realtor: "John Doe",
    detail:
      "Hilltop Manor offers breathtaking views and elegant living with 4 bedrooms and 3 bathrooms. The 1.2-acre lot provides a serene environment, while the spacious interior features modern amenities and stylish finishes. This manor is perfect for families seeking a luxurious home in Smallville.",
    featured_image: "/images/home-4.jpg",
  },
  {
    id: 5,
    listingId: "567-8901-23",
    name: "Lakeside Retreat",
    address: "654 Lakeview Ave",
    city: "Star City",
    state: "CA",
    zip: "90001",
    price: 950000,
    square_foot: 3000,
    bedrooms: 4,
    lot_size: 1.5,
    bathrooms: 3,
    listing_date: "2023-03-30",
    garage: 3,
    realtor: "Bruce Wayne",
    detail:
      "Lakeside Retreat is a stunning 4-bedroom home with beautiful lake views. This property features 3 bathrooms, a large 1.5-acre lot, and a spacious 3-car garage. The retreat offers modern amenities and a peaceful atmosphere, making it an ideal home for those seeking tranquility and luxury in Star City.",
    featured_image: "/images/home-5.jpg",
  },
  {
    id: 6,
    listingId: "678-9012-34",
    name: "Sunset Villa",
    address: "987 Sunset Blvd",
    city: "Central City",
    state: "FL",
    zip: "33101",
    price: 1100000,
    square_foot: 3400,
    bedrooms: 5,
    lot_size: 2.5,
    bathrooms: 4,
    listing_date: "2023-02-15",
    garage: 4,
    realtor: "Kent Clark",
    detail:
      "Sunset Villa is a magnificent 5-bedroom home with breathtaking sunset views. The property features 4 bathrooms, a large 2.5-acre lot, and a spacious 4-car garage. This villa offers high-end finishes and luxurious amenities, making it the perfect choice for those seeking an exquisite living experience in Central City.",
    featured_image: "/images/home-6.jpg",
  },
];

export const realtorsData = [
  {
    id: 1,
    name: "Jenny Johnson",
    phone: "(333)-333-3333",
    email: "jenny@example.com",
    bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis officia omnis non rerum dicta cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad fugit. Possimus culpa blanditiis repellendus ipsa similique ullam, natus error dolor harum.",
    facebookLink: "https://facebook.com",
    linkdeinLink: "https://linkdein.com",
    instagramLink: "https://instagram.com",
  },
  {
    id: 2,
    name: "Mark Hudson",
    phone: "(444)-444-4444",
    email: "mark@example.com",
    bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis officia omnis non rerum dicta cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad fugit. Possimus culpa blanditiis repellendus ipsa similique ullam, natus error dolor harum.",
    facebookLink: "https://facebook.com",
    linkdeinLink: "https://linkdein.com",
    instagramLink: "https://instagram.com",
  },
  {
    id: 3,
    name: "Kyle Brown",
    phone: "(555)-555-5555",
    email: "kyle@example.com",
    bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis officia omnis non rerum dicta cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad fugit. Possimus culpa blanditiis repellendus ipsa similique ullam, natus error dolor harum.",
    facebookLink: "https://facebook.com",
    linkdeinLink: "https://linkdein.com",
    instagramLink: "https://instagram.com",
  },
];
